twist_mux:
  ros__parameters:
    use_stamped: false
    output_topic: /diff_cont/cmd_vel_unstamped
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      joy:
        topic: /joy_vel
        timeout: 0.5
        priority: 10
      keyboard:
        topic: /keyboard_vel
        timeout: 0.5
        priority: 10
